POST http://localhost:8081/transfer/
Content-Type: application/json

{
    "transactionType":"NEFT",
    "transactionFrom":45676545678765,
    "transactionTo":7654567864,
    "transactionAmount":8
}

###
POST http://localhost:8081/account/2
Content-Type: application/json

{
    "accountType":"Fixed Deposit",
    "accountNumber":987858585,
    "accountBalance":98000.4,
    "accountStatus":true
}
###
GET http://localhost:8081/account/4
###
GET http://localhost:8081/account/
###
GET http://localhost:8081/customer/sabari
###
GET http://localhost:8081/customer/
###
POST http://localhost:8081/customer/
Content-Type: application/json

{
    "customerName":"Rajiya R",
    "customerAddress":"Salem",
    "customerStatus":true,
    "customerContact":888888888887,
    "username":"rajiya",
    "password":"mohamed"
}