PUT http://localhost:8081/crud/-1
Content-Type: application/json

Angular
###
DELETE http://localhost:8081/crud/0

###
POST http://localhost:8081/crud/
Content-Type: application/json

Angular

###
GET http://localhost:8081/crud/

###

POST http://localhost:8081/interview
Content-Type: application/json

Java
###
POST http://localhost:8081/interview
Content-Type: application/json

Git

###
GET http://localhost:8081/bmi/154/55
###
GET http://localhost:8081/bmi/172/92
###
GET http://localhost:8081/dtr/820

###

GET http://localhost:8081/bye

###

GET http://localhost:8081/hi

###

GET http://localhost:8081