PUT http://localhost:8081/savings/fine
###
DELETE http://localhost:8081/savings/bynum/8765678987
###
DELETE http://localhost:8081/savings/
###
PUT http://localhost:8081/savings/
Content-Type: application/json

{
    "accountHolder": "Hema priya",
    "accountNumber": 987656789,
    "accountBalance": 5259.6,
    "ifscCode": "ABCD00001",
    "bankName": "BHJD Bank"
}
###
GET http://localhost:8081/savings/accnum/949349345443434
###
GET http://localhost:8081/savings/accnum/112132323
###
GET http://localhost:8081/savings/100
###
POST http://localhost:8081/savings/
Content-Type: application/json

{
    "accountHolder": "Hema priya",
    "accountNumber": 112343434343,
    "accountBalance": 5259.6,
    "ifscCode": "ABCD00001",
    "bankName": "BHJD Bank"
}
###
GET http://localhost:8081/savings/
###
PUT http://localhost:8081/crud/-1
Content-Type: application/json

Angular
###
DELETE http://localhost:8081/crud/0

###
POST http://localhost:8081/crud/
Content-Type: application/json

Angular

###
GET http://localhost:8081/crud/

###

POST http://localhost:8081/interview
Content-Type: application/json

Java
###
POST http://localhost:8081/interview
Content-Type: application/json

Git

###
GET http://localhost:8081/bmi/154/55
###
GET http://localhost:8081/bmi/172/92
###
GET http://localhost:8081/dtr/820

###

GET http://localhost:8081/bye

###

GET http://localhost:8081/hi

###

GET http://localhost:8081