server:
  port: 8090
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/