GET http://localhost:8081/filter/256/20000
###
GET http://localhost:8081/laps
###
GET http://localhost:8081/price/30000
###
GET http://localhost:8081/cost/12501
###
GET http://localhost:8081/memory/511
###
DELETE http://localhost:8081/HP Pavilions
###
DELETE http://localhost:8081/
Content-Type: application/json

{
    "laptopModel":"HP Pavilion",
    "laptopSsd":120,
    "laptopPrice":33400
}
###
GET http://localhost:8081/HP Pavilion
###
GET http://localhost:8081/Compaq
###
POST http://localhost:8081/
Content-Type: application/json

{
    "laptopModel":"HP Pavilions",
    "laptopSsd":120,
    "laptopPrice":33400
}
###
GET http://localhost:8081/