###
# access auth service via gateway 
GET http://localhost:8090/customer/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyYWppeWEiLCJpYXQiOjE3NDY4NjI0NTYsImV4cCI6MTc0Njg2MjU2NH0.jH8bhghg9szvNjyxLqWPvKCsEuQBTRCH0_qBQ1epqi0
###
GET http://localhost:8090/account/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyYWppeWEiLCJpYXQiOjE3NDY4NjI0NTYsImV4cCI6MTc0Njg2MjU2NH0.jH8bhghg9szvNjyxLqWPvKCsEuQBTRCH0_qBQ1epqi0
###
POST http://localhost:8090/auth/signup
Content-Type: application/json

{
    "customerId": 4,
    "customerName": "Rajiya R",
    "customerAddress": "Salem",
    "customerStatus": true,
    "customerContact": 888888888887,
    "username": "rajiya",
    "password": "mohamed"
}

###
POST http://localhost:8090/auth/login
Content-Type: application/json

{
    "username":"rajiya",
    "password":"mohamed"
}
###

#auth service 
POST http://localhost:8094/auth/login
Content-Type: application/json

{
    "username":"rajiya",
    "password":"mohamed"
}

###
POST http://localhost:8094/auth/signup
Content-Type: application/json

{
    "customerId": 4,
    "customerName": "Rajiya R",
    "customerAddress": "Salem",
    "customerStatus": true,
    "customerContact": 888888888887,
    "username": "rajiya",
    "password": "mohamed"
}


###
#Via Gateway
GET http://localhost:8090/customer/
###
GET http://localhost:8090/account/

# security implemented in gateway service
GET http://localhost:8090/customer/
Authorization: Basic user:c63a540e-16f6-43a8-b44c-6367b0919353

# after included in customer-service spring security dependency/ generated password
# GET http://localhost:8090/customer/
# Authorization: Basic user:28bfde92-0280-4529-b356-1c992a25a589
###
GET http://localhost:8090/account/
Authorization: Basic user:c63a540e-16f6-43a8-b44c-6367b0919353
###

###
POST http://localhost:8093/account/
Content-Type: application/json

{
    "accountId": 5,
    "customer": 1,
    "accountType": "Fixed Deposit",
    "accountNumber": 987858585,
    "accountStatus": true,
    "accountBalance": 98000.4
}
###
GET http://localhost:8093/account/4
###
GET http://localhost:8093/account/
###
GET http://localhost:8091/customer/sabari
###
GET http://localhost:8091/customer/
###
POST http://localhost:8091/customer/
Content-Type: application/json

{
    "customerName":"Rajiya R",
    "customerAddress":"Salem",
    "customerStatus":true,
    "customerContact":888888888887,
    "username":"rajiya",
    "password":"mohamed"
}