###
POST http://localhost:8092/account/
Content-Type: application/json

{
    "accountId": 5,
    "customer": 1,
    "accountType": "Fixed Deposit",
    "accountNumber": 987858585,
    "accountStatus": true,
    "accountBalance": 98000.4
}
###
GET http://localhost:8092/account/4
###
GET http://localhost:8092/account/
###
GET http://localhost:8091/customer/sabari
###
GET http://localhost:8091/customer/
###
POST http://localhost:8091/customer/
Content-Type: application/json

{
    "customerName":"Rajiya R",
    "customerAddress":"Salem",
    "customerStatus":true,
    "customerContact":888888888887,
    "username":"rajiya",
    "password":"mohamed"
}