###
#auth service 

###
POST http://localhost:8094/auth/signup
Content-Type: application/json

{
    "customerId":2,
    "customerName":"Razak Moahmed S",
    "customerAddress":"Salem",
    "customerStatus":true,
    "customerContact":888888888887,
    "username":"razak",
    "password":"mohamed"
}


###
#Via Gateway

# security implemented in gateway service
GET http://localhost:8090/customer/
Authorization: Basic user:fbd0e7ae-7330-4684-b792-7dce135f8828

# after included in customer-service spring security dependency/ generated password
# GET http://localhost:8090/customer/
# Authorization: Basic user:28bfde92-0280-4529-b356-1c992a25a589
###
GET http://localhost:8090/account/
#Authorization: Basic user:09d5380e-8f8b-4dcf-ab7d-a941658d08e5
###

###
POST http://localhost:8093/account/
Content-Type: application/json

{
    "accountId": 5,
    "customer": 1,
    "accountType": "Fixed Deposit",
    "accountNumber": 987858585,
    "accountStatus": true,
    "accountBalance": 98000.4
}
###
GET http://localhost:8093/account/4
###
GET http://localhost:8093/account/
###
GET http://localhost:8091/customer/sabari
###
GET http://localhost:8091/customer/
###
POST http://localhost:8091/customer/
Content-Type: application/json

{
    "customerName":"Rajiya R",
    "customerAddress":"Salem",
    "customerStatus":true,
    "customerContact":888888888887,
    "username":"rajiya",
    "password":"mohamed"
}